#!/usr/bin/env bash
set -euo pipefail

# Install console-ssh-dispatch and generate an sshd drop-in config
# covering port 22 (Console Server CLI for group members) and a range
# (e.g., 20001..20024) for direct seriald attach for all users.
#
# Usage:
#   sudo tools/seriald/install_ssh_dispatch.sh -s 20001 -e 20024
#
# Flags:
#   -s START       Start port (default: 20001)
#   -e END         End port (default: 20024)
#   -c PATH        Drop-in file path (default: /etc/ssh/sshd_config.d/console-seriald.conf)
#   -n             Print config to stdout only (no write)
#   -d             Dry-run: show actions without executing
#
# Notes:
# - We write explicit LocalPort lists (comma-separated) for compatibility across OpenSSH versions.
# - Ensure /usr/local/bin/console-cli and /usr/local/bin/seriald-client are installed.

START_PORT=20001
END_PORT=20024
DROPIN="/etc/ssh/sshd_config.d/console-seriald.conf"
PRINT_ONLY=0
DRY_RUN=0

while getopts ":s:e:c:nd" opt; do
  case "$opt" in
    s) START_PORT="$OPTARG" ;;
    e) END_PORT="$OPTARG" ;;
    c) DROPIN="$OPTARG" ;;
    n) PRINT_ONLY=1 ;;
    d) DRY_RUN=1 ;;
    *) echo "Usage: $0 [-s start] [-e end] [-c dropin] [-n] [-d]" >&2; exit 2 ;;
  esac
done

if ! [[ "$START_PORT" =~ ^[0-9]+$ && "$END_PORT" =~ ^[0-9]+$ && $START_PORT -le $END_PORT ]]; then
  echo "Invalid port range: $START_PORT..$END_PORT" >&2
  exit 2
fi

# Build port list
PORTS=()
for ((p=START_PORT; p<=END_PORT; p++)); do
  PORTS+=("$p")
done
PORT_LIST_COMMAS=$(IFS=, ; echo "${PORTS[*]}")

# Generate config content
CONFIG_OUT="# Generated by install_ssh_dispatch.sh
# Ports for CLI and direct seriald attach
Port 22
"
for p in "${PORTS[@]}"; do
  CONFIG_OUT+="Port ${p}
"
done
CONFIG_OUT+="
# 1) Port 22 → Console Server CLI (group-based)
#    Only members of group 'console' are forced into the CLI; others get their normal shell.
Match Group console LocalPort 22
  ForceCommand /usr/local/bin/console-cli
  PermitTTY yes

# 2) Direct attach via dispatch wrapper (all users)
#    Computes --line from target port (line = port - 20000)
"

# Emit per-port Match blocks
for p in "${PORTS[@]}"; do
  CONFIG_OUT+="Match LocalPort ${p}
  ForceCommand /usr/local/bin/console-ssh-dispatch
  PermitTTY yes
  AllowTcpForwarding no
  X11Forwarding no

"
done

# Actions
copy_dispatch() {
  local src="$(dirname "$0")/console-ssh-dispatch.sh"
  local dst="/usr/local/bin/console-ssh-dispatch"
  if [[ $DRY_RUN -eq 1 ]]; then
    echo "DRY-RUN: install -m 0755 ${src} ${dst}"
  else
    install -m 0755 "$src" "$dst"
    echo "Installed ${dst}"
  fi
}

write_dropin() {
  if [[ $PRINT_ONLY -eq 1 ]]; then
    echo "$CONFIG_OUT"
    return 0
  fi
  if [[ $DRY_RUN -eq 1 ]]; then
    echo "DRY-RUN: write ${DROPIN} with below content:" && echo "$CONFIG_OUT"
  else
    mkdir -p "$(dirname "$DROPIN")"
    printf "%s" "$CONFIG_OUT" > "$DROPIN"
    echo "Wrote ${DROPIN}"
    echo "Reload sshd: sudo systemctl reload sshd"
  fi
}

copy_dispatch
write_dropin
