#!/usr/bin/env python3
import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional
from passlib.hash import sha512_crypt


def run(cmd, dry_run=False):
    if dry_run:
        print("DRY-RUN:", " ".join(cmd))
        return 0
    return subprocess.check_call(cmd)


def ensure_root():
    if os.geteuid() != 0:
        print("This command must be run as root. Try with sudo.", file=sys.stderr)
        sys.exit(1)


def read_users_file(path):
    users = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            users.append(line)
    return users


def ensure_group(group, dry_run=False):
    try:
        subprocess.check_call(["getent", "group", group], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print(f"Group '{group}' exists.")
    except subprocess.CalledProcessError:
        print(f"Creating group '{group}'...")
        run(["groupadd", "-f", group], dry_run=dry_run)


def ensure_user(user, shell, create, password=None, dry_run=False):
    exists = (subprocess.call(["id", "-u", user], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL) == 0)
    if exists:
        return True
    if not create:
        print(f"User '{user}' does not exist. Use --create-users to create.", file=sys.stderr)
        return False
    print(f"Creating user '{user}' with shell '{shell}'...")
    cmd = ["useradd", "-m", "-s", shell]
    if password:
        cmd.extend(["-p", sha512_crypt.hash(password)])
    cmd.append(user)
    run(cmd, dry_run=dry_run)
    if not password:
        print(f"Warning: user '{user}' created without a password and is locked.", file=sys.stderr)
    return True


def add_user_to_group(user, group, dry_run=False):
    print(f"Adding '{user}' to group '{group}'...")
    run(["usermod", "-aG", group, user], dry_run=dry_run)


def install_dispatch_wrapper(repo_dir, dry_run=False):
    src = Path(repo_dir) / "console-ssh-dispatch.sh"
    dst = Path("/usr/local/bin/console-ssh-dispatch")
    if not src.is_file():
        print(f"Dispatch wrapper not found at {src}", file=sys.stderr)
        sys.exit(2)
    if dry_run:
        print(f"DRY-RUN: install -m 0755 {src} {dst}")
    else:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        os.chmod(dst, 0o755)
        print(f"Installed {dst}")


def build_config(start_port, end_port, group, include_ports=True, address_family="any", include_port22=True, extra_ports=None):
    ports = list(range(start_port, end_port + 1))
    lines = []
    lines.append("# Generated by setup_ssh_dispatch.py")
    lines.append("# Ports for CLI and direct seriald attach")
    # Optional AddressFamily to reduce listen sockets (inet = IPv4 only)
    if address_family in ("inet", "inet6"):
        lines.append(f"AddressFamily {address_family}")
    if include_ports:
        if include_port22:
            lines.append("Port 22")
        for p in ports:
            lines.append(f"Port {p}")
    # Always include any extra single ports (e.g., redirect listen port) if requested
    if extra_ports:
        for ep in extra_ports:
            lines.append(f"Port {ep}")
    lines.append("")
    # Group-based port 22 → console-cli (others get normal shell) only if included
    if include_port22:
        lines.append("# 1) Port 22 → Console Server CLI (group-based)")
        lines.append("#    Only members of the group are forced into the CLI; others get their normal shell.")
        lines.append(f"Match Group {group} LocalPort 22")
        lines.append("    ForceCommand /usr/local/bin/console-cli")
        lines.append("    PermitTTY yes")
        lines.append("")
    # Direct attach via dispatch wrapper (all users)
    lines.append("# 2) Direct attach via dispatch wrapper (all users)")
    lines.append("#    Computes --line from target port (line = port - 20000)")
    for p in ports:
        lines.append(f"Match LocalPort {p}")
        lines.append("    ForceCommand /usr/local/bin/console-ssh-dispatch")
        lines.append("    PermitTTY yes")
        lines.append("    AllowTcpForwarding no")
        lines.append("    X11Forwarding no")
        lines.append("")
    # Also add wrapper mapping for any extra ports (e.g., NAT redirect listen port)
    if extra_ports:
        for ep in extra_ports:
            lines.append(f"Match LocalPort {ep}")
            lines.append("    ForceCommand /usr/local/bin/console-ssh-dispatch")
            lines.append("    PermitTTY yes")
            lines.append("    AllowTcpForwarding no")
            lines.append("    X11Forwarding no")
            lines.append("")
    return "\n".join(lines)


def write_dropin(config_text, dropin_path, print_only=False, dry_run=False):
    if print_only:
        print(config_text)
        return
    dropin = Path(dropin_path)
    if dry_run:
        print(f"DRY-RUN: write {dropin} with below content:\n{config_text}")
        return
    dropin.parent.mkdir(parents=True, exist_ok=True)
    dropin.write_text(config_text, encoding="utf-8")
    print(f"Wrote {dropin}")


def reload_sshd(dry_run=False):
    try:
        run(["systemctl", "reload", "sshd"], dry_run=dry_run)
        print("Reloaded sshd")
    except subprocess.CalledProcessError as e:
        print(f"Warning: failed to reload sshd: {e}", file=sys.stderr)


def remove_user_from_group(user, group, dry_run=False):
    print(f"Removing '{user}' from group '{group}'...")
    run(["gpasswd", "-d", user, group], dry_run=dry_run)


def delete_user(user, remove_home=False, force=False, dry_run=False):
    cmd = ["userdel"]
    if force:
        cmd.append("-f")
    if remove_home:
        cmd.append("-r")
    cmd.append(user)
    print(f"Deleting user '{user}' (remove_home={remove_home}, force={force})...")
    run(cmd, dry_run=dry_run)


def terminate_user_sessions(user, dry_run=False):
    # Terminate user sessions via systemd (if available)
    print(f"Terminating systemd sessions for user '{user}'...")
    try:
        run(["loginctl", "terminate-user", user], dry_run=dry_run)
    except subprocess.CalledProcessError as e:
        print(f"Warning: loginctl failed for {user}: {e}", file=sys.stderr)


def kill_user_processes(user, dry_run=False):
    # Send TERM to all user processes
    print(f"Killing processes for user '{user}' (SIGTERM)...")
    try:
        run(["pkill", "-u", user], dry_run=dry_run)
    except subprocess.CalledProcessError as e:
        print(f"Info: pkill returned non-zero (may be no processes): {e}")


def write_file(path: str, content: str, dry_run: bool = False):
    p = Path(path)
    if dry_run:
        print(f"DRY-RUN: write {path} with below content:\n{content}")
        return
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    print(f"Wrote {path}")


def create_secondary_sshd(start_port: int, end_port: int, address_family: str, config_path: str, service_name: str, group: str, dry_run: bool = False):
    print(f"Creating secondary sshd instance for ports {start_port}..{end_port}")
    cfg = build_config(start_port, end_port, group=group, include_ports=True, address_family=address_family, include_port22=False)
    write_file(config_path, cfg, dry_run=dry_run)
    unit_path = f"/etc/systemd/system/{service_name}"
    unit_content = """
[Unit]
Description=OpenSSH server (seriald secondary instance)
After=network.target

[Service]
ExecStart=/usr/sbin/sshd -D -f {config_path}
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
""".strip().format(config_path=config_path)
    write_file(unit_path, unit_content, dry_run=dry_run)
    if dry_run:
        print(f"DRY-RUN: systemctl daemon-reload && systemctl enable --now {service_name}")
    else:
        try:
            run(["systemctl", "daemon-reload"], dry_run=False)
            run(["systemctl", "enable", "--now", service_name], dry_run=False)
            print(f"Enabled and started {service_name}")
        except subprocess.CalledProcessError as e:
            print(f"Warning: failed to enable/start {service_name}: {e}", file=sys.stderr)


def ensure_firewall_redirect_iptables(start_port: int, end_port: int, to_port: int, include_output: bool, persist: bool, dry_run: bool = False) -> None:
    """Idempotently add iptables NAT REDIRECT rules to map a port range to a single port.

    - Adds PREROUTING rule: tcp dport start:end → REDIRECT to to_port
    - Optionally adds OUTPUT rule for local-origin testing
    - Uses `iptables -C` to check before appending, preventing duplicates
    - Optionally persists rules via netfilter-persistent or iptables-save
    """
    import shutil as _sh
    if _sh.which("iptables") is None:
        print("iptables not found; skipping firewall redirect.", file=sys.stderr)
        return

    range_spec = f"{start_port}:{end_port}"
    rules = [
        ("PREROUTING", ["-t", "nat", "-C", "PREROUTING", "-p", "tcp", "--dport", range_spec, "-j", "REDIRECT", "--to-ports", str(to_port)],
         ["-t", "nat", "-A", "PREROUTING", "-p", "tcp", "--dport", range_spec, "-j", "REDIRECT", "--to-ports", str(to_port)])
    ]
    if include_output:
        rules.append(
            ("OUTPUT", ["-t", "nat", "-C", "OUTPUT", "-p", "tcp", "--dport", range_spec, "-j", "REDIRECT", "--to-ports", str(to_port)],
             ["-t", "nat", "-A", "OUTPUT", "-p", "tcp", "--dport", range_spec, "-j", "REDIRECT", "--to-ports", str(to_port)])
        )

    for chain, check_cmd, add_cmd in rules:
        try:
            if dry_run:
                print("DRY-RUN:", "iptables", *check_cmd)
                print("DRY-RUN:", "iptables", *add_cmd)
                continue
            subprocess.check_call(["iptables", *check_cmd], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            print(f"Firewall redirect rule already present ({chain}).")
        except subprocess.CalledProcessError:
            print(f"Adding firewall redirect rule ({chain}) {range_spec} -> {to_port}...")
            subprocess.check_call(["iptables", *add_cmd])

    if persist:
        if dry_run:
            print("DRY-RUN: persist firewall rules via netfilter-persistent or iptables-save")
            return
        # Prefer netfilter-persistent, else write /etc/iptables/rules.v4 from iptables-save
        if _sh.which("netfilter-persistent") is not None:
            try:
                subprocess.check_call(["netfilter-persistent", "save"])
                print("Persisted firewall rules with netfilter-persistent.")
                return
            except subprocess.CalledProcessError as e:
                print(f"Warning: netfilter-persistent save failed: {e}", file=sys.stderr)
        try:
            out = subprocess.check_output(["iptables-save"], text=True)
            rules_dir = Path("/etc/iptables")
            rules_dir.mkdir(parents=True, exist_ok=True)
            (rules_dir / "rules.v4").write_text(out, encoding="utf-8")
            print("Persisted firewall rules to /etc/iptables/rules.v4.")
        except Exception as e:
            print(f"Warning: failed to persist iptables rules: {e}", file=sys.stderr)

def ensure_include(file_path: str, include_line: str, dry_run: bool = False) -> None:
    """Ensure an Include directive exists and is uncommented in a config file.

    - If the exact include_line is present and uncommented, do nothing.
    - If a commented version exists (e.g., '# Include ...'), uncomment it.
    - If missing, insert the include_line at the top of the file.
    """
    path = Path(file_path)
    if not path.exists():
        print(f"Info: {file_path} not found; skipping include check.")
        return
    try:
        content = path.read_text(encoding="utf-8").splitlines(keepends=True)
    except Exception as e:
        print(f"Warning: failed to read {file_path}: {e}", file=sys.stderr)
        return

    active_idx: Optional[int] = None
    commented_idx: Optional[int] = None
    for i, line in enumerate(content):
        stripped = line.strip()
        if stripped == include_line:
            active_idx = i
            break
        if stripped.startswith("#"):
            stripped_no_hash = stripped.lstrip("#").strip()
            if stripped_no_hash == include_line:
                commented_idx = i
                # continue scan in case an active one exists later

    if active_idx is not None:
        print(f"Include already active in {file_path}: {include_line}")
        return

    if commented_idx is not None:
        print(f"Uncommenting Include in {file_path}: {include_line}")
        content[commented_idx] = include_line + ("\n" if not content[commented_idx].endswith("\n") else "")
    else:
        print(f"Adding Include to {file_path}: {include_line}")
        content.insert(0, include_line + "\n")

    if dry_run:
        print(f"DRY-RUN: write {file_path} with updated Include")
        return
    try:
        Path(file_path).write_text("".join(content), encoding="utf-8")
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error writing {file_path}: {e}", file=sys.stderr)


def comment_out_include(file_path: str, include_line: str, dry_run: bool = False) -> None:
    """Comment out an Include line in a config file if it is active.

    If the exact line exists uncommented, prefix it with '# '. If already commented or missing, do nothing.
    """
    path = Path(file_path)
    if not path.exists():
        print(f"Info: {file_path} not found; skipping client include comment.")
        return
    try:
        content = path.read_text(encoding="utf-8").splitlines(keepends=True)
    except Exception as e:
        print(f"Warning: failed to read {file_path}: {e}", file=sys.stderr)
        return
    changed = False
    for i, line in enumerate(content):
        if line.strip() == include_line:
            content[i] = "# " + include_line + ("\n" if not content[i].endswith("\n") else "")
            changed = True
            print(f"Commented out Include in {file_path}: {include_line}")
            break
    if not changed:
        print(f"No active Include to comment in {file_path}.")
        return
    if dry_run:
        print(f"DRY-RUN: write {file_path} with commented Include")
        return
    try:
        path.write_text("".join(content), encoding="utf-8")
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error writing {file_path}: {e}", file=sys.stderr)


def parse_args():
    parser = argparse.ArgumentParser(description="Install SSH dispatch and manage console users")
    # Per-user mapping removed: direct-attach ports apply to all users
    parser.add_argument("--remove-all", action="store_true", help="Remove all seriald-related users, groups, SSH configs, services, and files (full uninstall)")
    parser.add_argument("-s", "--start", type=int, default=20001, help="Start port (default 20001)")
    parser.add_argument("-e", "--end", type=int, default=20024, help="End port (default 20024)")
    parser.add_argument("-c", "--config", default="/etc/ssh/sshd_config.d/console-seriald.conf", help="Drop-in path")
    parser.add_argument("-g", "--group", default="console", help="Group name for port 22 CLI access")
    parser.add_argument("--users", nargs="*", default=[], help="Users to add to the group")
    parser.add_argument("--users-file", help="File with usernames (one per line)")
    parser.add_argument("--create-users", action="store_true", help="Create users if missing")
    parser.add_argument("--shell", default="/bin/bash", help="Login shell for created users")
    parser.add_argument("--password", help="Password for created users. If not set, the account is locked.")
    parser.add_argument("--address-family", choices=["any", "inet", "inet6"], default="any", help="Address family for listening sockets (any=dual-stack, inet=IPv4 only, inet6=IPv6 only)")
    parser.add_argument("--no-ports", action="store_true", help="Do not emit Port lines in drop-in")
    parser.add_argument("--print-only", action="store_true", help="Print config to stdout, do not write")
    parser.add_argument("--dry-run", action="store_true", help="Show actions without executing")
    parser.add_argument("--no-reload", action="store_true", help="Do not reload sshd after writing config")
    parser.add_argument("--no-install-dispatch", action="store_true", help="Skip installing console-ssh-dispatch")
    parser.add_argument("--no-fix-include", action="store_true", help="Do not modify Include directives in sshd_config")
    parser.add_argument("--comment-client-include", action="store_true", help="Comment out Include /etc/ssh/sshd_config.d/*.conf in /etc/ssh/ssh_config if present")
    # User deletion/removal options
    parser.add_argument("--delete-users", nargs="*", default=[], help="Delete specified user accounts")
    parser.add_argument("--delete-users-file", help="File with usernames to delete (one per line)")
    parser.add_argument("--remove-home", action="store_true", help="When deleting users, remove home directories (-r)")
    parser.add_argument("--remove-from-group", action="store_true", help="Only remove users from the console group, do not delete accounts")
    parser.add_argument("--delete-only", action="store_true", help="Only perform user deletion/removal and skip sshd or wrapper changes")
    parser.add_argument("--kill-user-sessions", action="store_true", help="Terminate user's systemd sessions before deletion")
    parser.add_argument("--kill-processes", action="store_true", help="Send SIGTERM to all processes for the user before deletion")
    parser.add_argument("--force", action="store_true", help="Pass -f to userdel to force deletion if needed")
    # Secondary sshd instance options
    parser.add_argument("--enable-second-sshd", action="store_true", help="Create and start a secondary sshd instance for additional ports")
    parser.add_argument("--second-sshd-config", default="/etc/ssh/sshd_config_seriald2", help="Config path for secondary sshd instance")
    parser.add_argument("--second-sshd-service", default="ssh-seriald2.service", help="Systemd unit name for secondary sshd instance")
    # Firewall redirect (iptables) options
    parser.add_argument("--enable-firewall-redirect", action="store_true", help="Enable iptables REDIRECT from --start..--end to --redirect-to-port (idempotent)")
    parser.add_argument("--redirect-to-port", type=int, default=20000, help="Target sshd port to redirect to (default 20000)")
    parser.add_argument("--redirect-output", action="store_true", help="Also redirect locally-originating connections (OUTPUT chain) for testing")
    parser.add_argument("--persist-firewall", action="store_true", help="Persist iptables rules using netfilter-persistent or iptables-save")
    return parser.parse_args()


def main():

    args = parse_args()
    ensure_root()

    # REMOVE-ALL logic: full uninstall
    if getattr(args, "remove_all", False):
        print("[remove-all] Removing all seriald-related users, groups, SSH configs, services, and files from system folders...")
        dry_run = getattr(args, "dry_run", False)
        # 1. Remove users in the console group (system users only)
        group = getattr(args, "group", "console")
        try:
            import pwd, grp
            group_info = grp.getgrnam(group)
            users_in_group = group_info.gr_mem
        except Exception as e:
            print(f"[remove-all] Warning: could not get users in group '{group}': {e}")
            users_in_group = []
        for u in users_in_group:
            try:
                print(f"[remove-all] Deleting user '{u}'...")
                terminate_user_sessions(u, dry_run=dry_run)
                kill_user_processes(u, dry_run=dry_run)
                delete_user(u, remove_home=True, force=True, dry_run=dry_run)
            except Exception as e:
                print(f"[remove-all] Warning: failed to delete user '{u}': {e}")
        # 2. Remove group
        try:
            print(f"[remove-all] Deleting group '{group}'...")
            if not dry_run:
                subprocess.call(["groupdel", group])
            else:
                print(f"DRY-RUN: groupdel {group}")
        except Exception as e:
            print(f"[remove-all] Warning: failed to delete group '{group}': {e}")
        # 3. Remove SSH drop-in config (system folder only)
        dropin = "/etc/ssh/sshd_config.d/console-seriald.conf"
        if Path(dropin).exists():
            print(f"[remove-all] Removing drop-in config {dropin}")
            if not dry_run:
                try:
                    Path(dropin).unlink()
                except Exception as e:
                    print(f"[remove-all] Warning: failed to remove {dropin}: {e}")
            else:
                print(f"DRY-RUN: rm {dropin}")
        # 4. Remove secondary sshd config and service (system folders only)
        second_cfg = "/etc/ssh/sshd_config_seriald2"
        second_srv = "ssh-seriald2.service"
        if Path(second_cfg).exists():
            print(f"[remove-all] Removing secondary sshd config {second_cfg}")
            if not dry_run:
                try:
                    Path(second_cfg).unlink()
                except Exception as e:
                    print(f"[remove-all] Warning: failed to remove {second_cfg}: {e}")
            else:
                print(f"DRY-RUN: rm {second_cfg}")
        unit_path = f"/etc/systemd/system/{second_srv}"
        if Path(unit_path).exists():
            print(f"[remove-all] Removing secondary sshd service {unit_path}")
            if not dry_run:
                try:
                    Path(unit_path).unlink()
                except Exception as e:
                    print(f"[remove-all] Warning: failed to remove {unit_path}: {e}")
            else:
                print(f"DRY-RUN: rm {unit_path}")
        # 5. Remove dispatch wrapper (system folder only)
        wrapper = "/usr/local/bin/console-ssh-dispatch"
        if Path(wrapper).exists():
            print(f"[remove-all] Removing dispatch wrapper {wrapper}")
            if not dry_run:
                try:
                    Path(wrapper).unlink()
                except Exception as e:
                    print(f"[remove-all] Warning: failed to remove {wrapper}: {e}")
            else:
                print(f"DRY-RUN: rm {wrapper}")
        # 6. Remove seriald systemd service (system folder only)
        seriald_service = "/etc/systemd/system/seriald.service"
        if Path(seriald_service).exists():
            print(f"[remove-all] Removing seriald service {seriald_service}")
            if not dry_run:
                try:
                    Path(seriald_service).unlink()
                except Exception as e:
                    print(f"[remove-all] Warning: failed to remove {seriald_service}: {e}")
            else:
                print(f"DRY-RUN: rm {seriald_service}")
        # 7. Reload systemd and sshd
        print("[remove-all] Reloading systemd and sshd...")
        if not dry_run:
            try:
                subprocess.call(["systemctl", "daemon-reload"])
                subprocess.call(["systemctl", "reload", "sshd"])
            except Exception as e:
                print(f"[remove-all] Warning: failed to reload systemd/sshd: {e}")
        else:
            print("DRY-RUN: systemctl daemon-reload && systemctl reload sshd")
        print("[remove-all] Complete.")
        return

    # Validate ports
    if args.start > args.end:
        print(f"Invalid port range: {args.start}..{args.end}", file=sys.stderr)
        sys.exit(2)

    # Compute repo dir (for locating wrapper)
    repo_dir = Path(__file__).resolve().parent

    # If delete-only is requested, execute deletions and exit before any sshd/wrapper changes.
    if args.delete_only:
        del_list = list(args.delete_users)
        if args.delete_users_file:
            del_list.extend(read_users_file(args.delete_users_file))
        if not del_list:
            print("No users specified for deletion. Use --delete-users or --delete-users-file.", file=sys.stderr)
            sys.exit(1)
        had_error = False
        for u in del_list:
            try:
                if args.remove_from_group:
                    remove_user_from_group(u, args.group, dry_run=args.dry_run)
                    continue
                if args.kill_user_sessions:
                    terminate_user_sessions(u, dry_run=args.dry_run)
                if args.kill_processes:
                    kill_user_processes(u, dry_run=args.dry_run)
                delete_user(u, remove_home=args.remove_home, force=args.force, dry_run=args.dry_run)
            except subprocess.CalledProcessError as e:
                print(f"Error: failed to delete user '{u}' (exit {e.returncode}). Try --kill-user-sessions, --kill-processes, or --force.", file=sys.stderr)
                had_error = True
        if had_error:
            sys.exit(1)
        return

    # Install dispatch wrapper
    if not args.no_install_dispatch:
        install_dispatch_wrapper(repo_dir, dry_run=args.dry_run)

    # Group and users management
    ensure_group(args.group, dry_run=args.dry_run)
    user_list = list(args.users)
    if args.users_file:
        user_list.extend(read_users_file(args.users_file))

    for u in user_list:
        if ensure_user(u, args.shell, args.create_users, password=args.password, dry_run=args.dry_run):
            add_user_to_group(u, args.group, dry_run=args.dry_run)

    # User deletion / removal from group
    del_list = list(args.delete_users)
    if args.delete_users_file:
        del_list.extend(read_users_file(args.delete_users_file))
    for u in del_list:
        if args.remove_from_group:
            remove_user_from_group(u, args.group, dry_run=args.dry_run)
        else:
            if args.kill_user_sessions:
                terminate_user_sessions(u, dry_run=args.dry_run)
            if args.kill_processes:
                kill_user_processes(u, dry_run=args.dry_run)
            delete_user(u, remove_home=args.remove_home, force=args.force, dry_run=args.dry_run)

    # Ensure server Include directive is active; do not modify client config by default
    if not args.no_fix_include:
        ensure_include("/etc/ssh/sshd_config", "Include /etc/ssh/sshd_config.d/*.conf", dry_run=args.dry_run)
    if args.comment_client_include:
        comment_out_include("/etc/ssh/ssh_config", "Include /etc/ssh/sshd_config.d/*.conf", dry_run=args.dry_run)

    # Generate and write drop-in config
    # Estimate listen sockets to warn about MAX_LISTEN_SOCKS (~16)
    sockets_per_port = 2 if args.address_family == "any" else 1
    total_ports = (0 if args.no_ports else (1 + (args.end - args.start + 1)))
    est_sockets = sockets_per_port * total_ports
    if total_ports > 0 and est_sockets > 16:
        print(f"Warning: estimated listen sockets {est_sockets} may exceed OpenSSH limit (~16). Consider --address-family inet or reducing port range.")

    cfg = build_config(
        start_port=args.start,
        end_port=args.end,
        group=args.group,
        include_ports=not args.no_ports,
        address_family=args.address_family,
        include_port22=True,
        extra_ports=[args.redirect_to_port] if args.enable_firewall_redirect else None,
    )
    write_dropin(cfg, args.config, print_only=args.print_only, dry_run=args.dry_run)

    # Optional: firewall redirect to a single sshd port
    if args.enable_firewall_redirect:
        ensure_firewall_redirect_iptables(
            start_port=args.start,
            end_port=args.end,
            to_port=args.redirect_to_port,
            include_output=args.redirect_output,
            persist=args.persist_firewall,
            dry_run=args.dry_run,
        )

    # Secondary sshd instance to extend port capacity if requested
    if args.enable_second_sshd:
        # Split the range into two halves: primary handles first half, secondary handles second half
        total = (args.end - args.start + 1)
        half = args.start + total // 2
        primary_start = args.start
        primary_end = half - 1 if total > 1 else args.end
        secondary_start = half if total > 1 else args.end
        secondary_end = args.end

        if not args.no_ports and total > 1:
            cfg_primary = build_config(
                start_port=primary_start,
                end_port=primary_end,
                group=args.group,
                include_ports=True,
                address_family=args.address_family,
                include_port22=True,
            )
            write_dropin(cfg_primary, args.config, print_only=args.print_only, dry_run=args.dry_run)

        create_secondary_sshd(
            start_port=secondary_start,
            end_port=secondary_end,
            address_family=args.address_family,
            config_path=args.second_sshd_config,
            service_name=args.second_sshd_service,
            group=args.group,
            dry_run=args.dry_run,
        )

    # Reload sshd if not suppressed and not print-only (primary instance)
    if not args.print_only and not args.no_reload:
        reload_sshd(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
